services:

  hitsto-app:
    container_name: hitsto-app
    image: hitsto:0.0.1
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - DB_USER=root
      - DB_PASS=hitsto
      - DB_HOST=hitsto-mysql-db
      - DB_NAME=hitsto_database
      - REDIS_HOST=hitsto-redis
      - REDIS_PORT=6379
    networks:
      - hitsto-network
    depends_on:
      hitsto-mysql-db:
        condition: service_healthy

  hitsto-mysql-db:
    container_name: hitsto-mysql-db
    image: mysql:8.0.34
    ports:
      - "33066:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hitsto
    networks:
      - hitsto-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-phitsto"]
      interval: 30s
      timeout: 10s
      retries: 3

  hitsto-redis:
    container_name: hitsto-redis
    image: redis:7.4.0-alpine
    ports:
      - "6379:6379"
    networks:
      - hitsto-network

networks:
  hitsto-network:
    name: hitsto-network
    driver: bridge
