apiVersion: v1
kind: Service
metadata:
  name: hitsto-app
spec:
  type: LoadBalancer
  ports:
    - name: http # Application port
      port: 8080
      targetPort: 8080
    - name: remote # Remote Debug port
      port: 5005
      targetPort: 5005
  selector:
    app: hitsto-app
